const { GAME_TYPE_CODE, GAME_TYPE_TEMPLATE_BY_CODE } = require('@config/constants/gameTypes');
const { MARKET_STATUS } = require('@config/constants/domain');

module.exports = Object.freeze([
  {
    code: GAME_TYPE_CODE.SINGLE,
    name: 'Single Digit',
    templateKey: GAME_TYPE_TEMPLATE_BY_CODE[GAME_TYPE_CODE.SINGLE],
    payoutMultiplier: 9.5,
    status: MARKET_STATUS.ACTIVE,
    version: 1,
  },
  {
    code: GAME_TYPE_CODE.JODI,
    name: 'Jodi',
    templateKey: GAME_TYPE_TEMPLATE_BY_CODE[GAME_TYPE_CODE.JODI],
    payoutMultiplier: 90,
    status: MARKET_STATUS.ACTIVE,
    version: 1,
  },
  {
    code: GAME_TYPE_CODE.SP,
    name: 'Single Pana',
    templateKey: GAME_TYPE_TEMPLATE_BY_CODE[GAME_TYPE_CODE.SP],
    payoutMultiplier: 150,
    status: MARKET_STATUS.ACTIVE,
    version: 1,
  },
  {
    code: GAME_TYPE_CODE.DP,
    name: 'Double Pana',
    templateKey: GAME_TYPE_TEMPLATE_BY_CODE[GAME_TYPE_CODE.DP],
    payoutMultiplier: 300,
    status: MARKET_STATUS.ACTIVE,
    version: 1,
  },
  {
    code: GAME_TYPE_CODE.TP,
    name: 'Triple Pana',
    templateKey: GAME_TYPE_TEMPLATE_BY_CODE[GAME_TYPE_CODE.TP],
    payoutMultiplier: 600,
    status: MARKET_STATUS.ACTIVE,
    version: 1,
  },
  {
    code: GAME_TYPE_CODE.HS_A,
    name: 'Half Sangam A',
    templateKey: GAME_TYPE_TEMPLATE_BY_CODE[GAME_TYPE_CODE.HS_A],
    payoutMultiplier: 1000,
    status: MARKET_STATUS.ACTIVE,
    version: 1,
  },
  {
    code: GAME_TYPE_CODE.HS_B,
    name: 'Half Sangam B',
    templateKey: GAME_TYPE_TEMPLATE_BY_CODE[GAME_TYPE_CODE.HS_B],
    payoutMultiplier: 1000,
    status: MARKET_STATUS.ACTIVE,
    version: 1,
  },
  {
    code: GAME_TYPE_CODE.FS,
    name: 'Full Sangam',
    templateKey: GAME_TYPE_TEMPLATE_BY_CODE[GAME_TYPE_CODE.FS],
    payoutMultiplier: 10000,
    status: MARKET_STATUS.ACTIVE,
    version: 1,
  },
  {
    code: GAME_TYPE_CODE.SP_MOTOR,
    name: 'SP Motor',
    templateKey: GAME_TYPE_TEMPLATE_BY_CODE[GAME_TYPE_CODE.SP_MOTOR],
    payoutMultiplier: 150,
    status: MARKET_STATUS.ACTIVE,
    version: 1,
  },
  {
    code: GAME_TYPE_CODE.DP_MOTOR,
    name: 'DP Motor',
    templateKey: GAME_TYPE_TEMPLATE_BY_CODE[GAME_TYPE_CODE.DP_MOTOR],
    payoutMultiplier: 300,
    status: MARKET_STATUS.ACTIVE,
    version: 1,
  },
]);
