module.exports = {
  User: require('./User'),
  Payment: require('./Payment'),
  Payout: require('./Payout'),
  BankDetail: require('./BankDetail'),
  GlobalConfig: require('./GlobalConfig'),
  GameSession: require('./GameSession'),
  Transaction: require('./Transaction'),
  Market: require('./Market'),
  Wallet: require('./Wallet'),
  Bet: require('./Bet'),
  GameType: require('./GameType'),
  Role: require('./Role'),
  Permission: require('./Permission'),
  UserRole: require('./UserRole'),
  RolePermission: require('./RolePermission'),
  EventTask: require('./EventTask'),
  SettlementJob: require('./SettlementJob'),
  RevertBatch: require('./RevertBatch'),
  ResultAuditRecord: require('./ResultAuditRecord'),
  Log: require('./Log'),
  UserDevice: require('./UserDevice'),
  SessionExposure: require('./SessionExposure'),
};
