module.exports = {
  MARKET_PHASE_CHANGE: 'MARKET_PHASE_CHANGE',
  MARKET_LOCK: 'MARKET_LOCK',
  SETTLE_OPEN_RESULT: 'SETTLE_OPEN_RESULT',
  SETTLE_CLOSE_RESULT: 'SETTLE_CLOSE_RESULT',
  PROCESS_REVERT_BATCH: 'PROCESS_REVERT_BATCH',
};
