const { TEMPLATE } = require('@domain/rule-engine/GameTypeRegistry');

const GAME_TYPE_CODE = Object.freeze({
  SINGLE: 'SINGLE',
  JODI: 'JODI',
  SP: 'SP',
  DP: 'DP',
  TP: 'TP',
  HS_A: 'HS_A',
  HS_B: 'HS_B',
  FS: 'FS',
  SP_MOTOR: 'SP_MOTOR',
  DP_MOTOR: 'DP_MOTOR',
});

const GAME_TYPE_CODES = Object.freeze(Object.values(GAME_TYPE_CODE));

const GAME_TYPE_TEMPLATE_BY_CODE = Object.freeze({
  [GAME_TYPE_CODE.SINGLE]: TEMPLATE.SINGLE_DIGIT,
  [GAME_TYPE_CODE.JODI]: TEMPLATE.JODI,
  [GAME_TYPE_CODE.SP]: TEMPLATE.SINGLE_PANA,
  [GAME_TYPE_CODE.DP]: TEMPLATE.DOUBLE_PANA,
  [GAME_TYPE_CODE.TP]: TEMPLATE.TRIPLE_PANA,
  [GAME_TYPE_CODE.HS_A]: TEMPLATE.HALF_SANGAM_A,
  [GAME_TYPE_CODE.HS_B]: TEMPLATE.HALF_SANGAM_B,
  [GAME_TYPE_CODE.FS]: TEMPLATE.FULL_SANGAM,
  [GAME_TYPE_CODE.SP_MOTOR]: TEMPLATE.SP_MOTOR,
  [GAME_TYPE_CODE.DP_MOTOR]: TEMPLATE.DP_MOTOR,
});

module.exports = {
  GAME_TYPE_CODE,
  GAME_TYPE_CODES,
  GAME_TYPE_TEMPLATE_BY_CODE,
};
