const PERMISSION_CODE = Object.freeze({
  ADMIN_ACCESS: 'ADMIN_ACCESS',
  USER_MANAGE: 'USER_MANAGE',
  MARKET_MANAGE: 'MARKET_MANAGE',
  GAME_TYPE_MANAGE: 'GAME_TYPE_MANAGE',
  RESULT_DECLARE: 'RESULT_DECLARE',
  PAYMENT_MANAGE: 'PAYMENT_MANAGE',
  REPORT_VIEW: 'REPORT_VIEW',
  NOTIFICATION_SEND: 'NOTIFICATION_SEND',
});

module.exports = {
  PERMISSION_CODE,
};
